Replace ack with grep and find. More robust script

diff --git a/check-project b/check-project
--- a/check-project
+++ b/check-project
@@ -3,22 +3,31 @@
 # 2020/06/11 Gabriel Moreau
 
 
-NB_SWMB=$(ack -i --ignore-dir Win10-Initial-Setup-Script '^Function[[:space:]](Enable|Disable)' | awk '{print $2}' | wc -l)
-NB_TOTAL=$(ack -i '^Function[[:space:]](Enable|Disable)' | awk '{print $2}' | wc -l)
+NB_SWMB=$(grep -hEi '^Function[[:space:]](Enable|Disable)' $(find . -path ./Win10-Initial-Setup-Script -prune -o -name '*.psm1' -print) | awk '{print $2}' | wc -l)
+NB_TOTAL=$(grep -hEi '^Function[[:space:]](Enable|Disable)' $(find . -name '*.psm1' -print) | awk '{print $2}' | wc -l)
 
 echo "Info: number of SWMB  rules: ${NB_SWMB} / $((${NB_SWMB}/2)) (enable and disable)"
 echo "Info: number of total rules: ${NB_TOTAL} / $((${NB_TOTAL}/2)) (enable and disable)"
 
-NB_DOUBLEDEF=$(ack -i '^Function[[:space:]](Enable|Disable)' | awk '{print $2}' | perl -pe 's/^(Enable|Disable)//i;'| sort | uniq -c | grep -v '^      2 ' | tr '\n' '&')
-if [ $(echo ${NB_DOUBLEDEF} | tr  '&' '\n' | head -n -1 | wc -l) -gt 0 ]
+NB_DOUBLEDEF=$(grep -hEi '^Function[[:space:]](Enable|Disable)' $(find . -name '*.psm1' -print) \
+   | awk '{print $2}' \
+   | perl -pe 's/^(Enable|Disable)//i;' \
+   | sort \
+   | uniq -c \
+   | grep -v '^      2 ' \
+   | tr '\n' '&')
+if [ $(echo ${NB_DOUBLEDEF} | tr '&' '\n' | head -n -1 | wc -l) -gt 0 ]
 then
-   echo ${NB_DOUBLEDEF} | tr  '&' '\n' | head -n -1 | awk '{print "Error: multiple (" $1/2 ") definition of function: " $2}'
+   echo ${NB_DOUBLEDEF} | tr '&' '\n' | head -n -1 | awk '{print "Error: multiple (" $1/2 ") definition of function: " $2}'
 fi
 
-for rule in $(ack -i --ignore-dir  Win10-Initial-Setup-Script '^Function[[:space:]](Enable)'| awk '{print $2}' | sed -e 's/^Enable//i;')
+for rule in $(grep -hEi '^Function[[:space:]](Enable|Disable)' $(find . -path ./Win10-Initial-Setup-Script -prune -o -name '*.psm1' -print) \
+   | awk '{print $2}' \
+   | sed -E -e 's/^(Enable|Disable)//i;' \
+   | sort -u)
 do
-   if ! egrep -q "^(#[[:space:]])?(Enable|Disable)${rule}" Presets/*
+   if ! grep -Eq "^(#[[:space:]])?(Enable|Disable)${rule}" Presets/*.preset
    then
-      echo "Warning, no preset proposed for rule: ${rule}"
+      echo "Warning: no preset proposed for rule: ${rule}"
    fi
 done
